# aot-compile-mp-4
# Autogenerated from man page /opt/local/share/man/man1/aot-compile-mp-4.7.1.gz
# using Type1
complete -c aot-compile-mp-4 -s M -l make --description 'Specify the path to the \\f(CW\\*(C`make\\*(C\' executable to use.'
complete -c aot-compile-mp-4 -s C -l gcj --description 'Specify the path to the \\f(CW\\*(C`gcj\\*(C\' executable to use.'
complete -c aot-compile-mp-4 -s D -l dbtool --description 'Specify the path to the \\f(CW\\*(C`gcj-dbtool\\*(… [See Man Page]'
complete -c aot-compile-mp-4 -s m -l makeflags --description 'Specify flags to pass to \\f(CW\\*(C`make\\*(C\' during the build.'
complete -c aot-compile-mp-4 -s c -l gcjflags --description 'Specify flags to pass to \\f(CW\\*(C`gcj\\*(C\' dur… [See Man Page]'
complete -c aot-compile-mp-4 -s l -l ldflags --description 'Specify flags to pass to \\f(CW\\*(C`gcj\\*(C\' dur… [See Man Page]'

