# biblio2yaml
# Autogenerated from man page /usr/local/share/man/man1/biblio2yaml.1
# using Deroffing man parser
complete -c biblio2yaml -l 'help\\f[]' --description 'Print usage information. RS . RE.'
complete -c biblio2yaml -l ---------- -l ------------ --description 'MODS              . mods BibLaTeX          .'
complete -c biblio2yaml -o f/--format --description 'OPTIONS.'
complete -c biblio2yaml -s f -l format --description 'Specify format of bibliography to be converted.'
complete -c biblio2yaml -s h -l help --description 'Print usage information.'
complete -c biblio2yaml -s V -l version --description 'Print version.  AUTHORS.'

