# bison
# Autogenerated from man page /opt/local/share/man/man1/bison.1.gz
# using Deroffing man parser
complete -c bison -l print-localedir --description 'output directory containing locale-dependent data.'
complete -c bison -l print-datadir --description 'output directory containing skeletons and XSLT.'
complete -c bison -s W -l 'warnings[' --description 'report the warnings falling in CATEGORY.'
complete -c bison -s f -l 'feature[' --description 'activate miscellaneous features . SS "Parser:".'
complete -c bison -s L -l language --description 'specify the output programming language.'
complete -c bison -s S -l skeleton --description 'specify the skeleton to use.'
complete -c bison -l locations --description 'enable location support.'
complete -c bison -s D -l define --description 'similar to \'%define NAME "VALUE"\'.'
complete -c bison -s F -l force-define --description 'override \'%define NAME "VALUE"\'.'
complete -c bison -l 'defines[' --description 'also produce a header file.'
complete -c bison -s r -l report --description 'also produce details on the automaton.'
complete -c bison -l report-file --description 'write report to FILE.'
complete -c bison -l output --description 'leave output to FILE.'
complete -c bison -l 'graph[' --description 'also output a graph of the automaton.'
complete -c bison -s x -l 'xml[' --description 'also output an XML report of the automaton (the… [See Man Page]'

