# checksyms
# Autogenerated from man page /opt/local/share/man/man1/checksyms.1.gz
# using Deroffing man parser
complete -c checksyms -s r --description 'The binary is expected to do runtime loading of… [See Man Page]'
complete -c checksyms -s d --description 'Print the detail of why the binary fails the checks.'
complete -c checksyms -s v --description 'Print a single string token for each of the che… [See Man Page]'
complete -c checksyms -s t --description 'Allow all symbols except debugging symbols (tho… [See Man Page]'
complete -c checksyms -s b --description 'Check the binaries that use the dynamic linker … [See Man Page]'
complete -c checksyms -o arch --description 'Specifies the architecture,  arch_type, in the file to check.'
complete -c checksyms -o dylib_table --description 'This specifies the filename of the table of dyn… [See Man Page]'
complete -c checksyms -o seg_addr_table --description 'This specifies the filename of the segment addr… [See Man Page]'
complete -c checksyms -s g --description 'option).'
complete -c checksyms -o 'seg1addr.' --description 'In the second form is used for ``split\'\' librar… [See Man Page]'
complete -c checksyms -o segs_read_only_addr --description 'address and the second address is the.'
complete -c checksyms -o segs_read_write_addr --description 'address.  If the.'
complete -c checksyms -o seg_addr_table_filename --description 'Use pathname instead of the install name of the… [See Man Page]'

