# check_dylib
# Autogenerated from man page /opt/local/share/man/man1/check_dylib.1.gz
# using Deroffing man parser
complete -c check_dylib -o install_name --description 'argument and if it does not match it exit with a value of 2.'
complete -c check_dylib -o seg_addr_table --description 'for an entry with the path_name argument of the.'
complete -c check_dylib -o seg_addr_table_filename --description 'and if one is not found in the table exit with a value of 3.'

