# curl
# Autogenerated from man page /usr/share/man/man1/curl.1
# using Deroffing man parser
complete -c curl -o z/--time-cond --description '(HTTP/FTP) Request a file that has been modifie… [See Man Page]'
complete -c curl -l 'netrc-optional.' --description '.'

