# gm4
# Autogenerated from man page /opt/local/share/man/man1/gm4.1.gz
# using Deroffing man parser
complete -c gm4 -s i --description 'unbuffer output, ignore interrupts.'
complete -c gm4 -l 'warn-macro-sequence[' --description 'warn if macro definition matches REGEXP, P defa… [See Man Page]'
complete -c gm4 -s g -l gnu --description 'override -G to re-enable GNU extensions.'
complete -c gm4 -l 'debugfile[' --description 'redirect debug and trace output to FILE (defaul… [See Man Page]'

