# gorbd-mp-4
# Autogenerated from man page /opt/local/share/man/man1/gorbd-mp-4.7.1.gz
# using Type1
complete -c gorbd-mp-4 -o ORBInitialPort --description 'Port on which persistent naming service is to be started.'
complete -c gorbd-mp-4 -o ior --description 'File in which to store persistent naming servic… [See Man Page]'
complete -c gorbd-mp-4 -o directory --description 'Directory in which to store persistent data.'
complete -c gorbd-mp-4 -o restart --description 'Restart persistent naming service, clearing per… [See Man Page]'
complete -c gorbd-mp-4 -o help --description 'Print help text, then exit.'
complete -c gorbd-mp-4 -o version --description 'Print version number, then exit.'

