# grmid-mp-4
# Autogenerated from man page /opt/local/share/man/man1/grmid-mp-4.7.1.gz
# using Type1
complete -c grmid-mp-4 -o port --description 'Port on which activation system is to be started.'
complete -c grmid-mp-4 -o restart --description 'Restart activation system, clearing persistent … [See Man Page]'
complete -c grmid-mp-4 -o stop --description 'Stop activation system. PP Persistence:.'
complete -c grmid-mp-4 -o persistent --description 'Make activation system persistent.'
complete -c grmid-mp-4 -o directory --description 'Directory in which to store persistent data. PP Debugging:.'
complete -c grmid-mp-4 -o verbose --description 'Log binding events to standard out. PP Standard options:.'
complete -c grmid-mp-4 -o help --description 'Print help text, then exit.'
complete -c grmid-mp-4 -o version --description 'Print version number, then exit.'

