# grmiregistry-mp-4
# Autogenerated from man page /opt/local/share/man/man1/grmiregistry-mp-4.7.1.gz
# using Type1
complete -c grmiregistry-mp-4 -o restart --description 'Restart \\s-1RMI\\s0 naming service, clearing per… [See Man Page]'
complete -c grmiregistry-mp-4 -o stop --description 'Stop \\s-1RMI\\s0 naming service. PP Persistence:.'
complete -c grmiregistry-mp-4 -o persistent --description 'Make \\s-1RMI\\s0 naming service persistent.'
complete -c grmiregistry-mp-4 -o directory --description 'Directory in which to store persistent data. PP Debugging:.'
complete -c grmiregistry-mp-4 -o verbose --description 'Log binding events to standard out. PP Standard options:.'
complete -c grmiregistry-mp-4 -o help --description 'Print help text, then exit.'
complete -c grmiregistry-mp-4 -o version --description 'Print version number, then exit.'

