# gserialver-mp-4
# Autogenerated from man page /opt/local/share/man/man1/gserialver-mp-4.7.1.gz
# using Type1
complete -c gserialver-mp-4 -o classpath --description 'Class path to use to find classes. PP Standard options:.'
complete -c gserialver-mp-4 -o help --description 'Print help text, then exit.'
complete -c gserialver-mp-4 -o version --description 'Print version number, then exit.'

