# gtnameserv-mp-4
# Autogenerated from man page /opt/local/share/man/man1/gtnameserv-mp-4.7.1.gz
# using Type1
complete -c gtnameserv-mp-4 -o ORBInitialPort --description 'Port on which naming service is to be started.'
complete -c gtnameserv-mp-4 -o ior --description 'File in which to store naming service\'s \\s-1IOR\\s0 reference.'
complete -c gtnameserv-mp-4 -o help --description 'Print help text, then exit.'
complete -c gtnameserv-mp-4 -o version --description 'Print version number, then exit.'

