# guile
# Autogenerated from man page /opt/local/share/man/man1/guile.1.gz
# using Deroffing man parser
complete -c guile -s l --description 'Load scheme source code from file.'
complete -c guile -s e --description 'After reading script, apply FUNCTION to command-line arguments.'
complete -c guile -o ds --description 'do -s SCRIPT at this point (note that this argu… [See Man Page]'
complete -c guile -l help --description 'Describe command line options and exit.'
complete -c guile -l debug --description 'Start guile with debugging evaluator and backtr… [See Man Page]'
complete -c guile -l version --description 'Display guile version and exit.'
complete -c guile -l emacs --description 'Enable emacs protocol for use from within emacs (experimental).'
complete -c guile -s c --description 'Stop argument processing, evaluate EXPR as a scheme expression.'
complete -c guile -s s --description 'Load Scheme source from SCRIPT-FILE and execute as a script.'

