# indr
# Autogenerated from man page /opt/local/share/man/man1/indr.1.gz
# using Deroffing man parser
complete -c indr -s n --description 'Suppress creating the indirect objects when the… [See Man Page]'
complete -c indr -o arch --description 'Specifies the architecture,  arch_type, of the … [See Man Page]'

