# kinit
# Autogenerated from man page /usr/share/man/man1/kinit.1
# using Darwin man parser
complete -c kinit -l renewable --description 'The same as renewable-life, with an infinite time.'
complete -c kinit -s e --description 'Request tickets with this particular enctype.'
complete -c kinit -l password-file --description 'read the password from the first line of filename.'
complete -c kinit -l fcache-version --description 'Create a credentials cache of version version-number.'
complete -c kinit -l anonymous --description 'Request an anonymous ticket (which means that t… [See Man Page]'
complete -c kinit -l enterprise --description 'Parse principal as a enterprise (KRB5-NT-ENTERPRISE) name.'
complete -c kinit -l afslog --description 'Gets AFS tickets, converts them to version 4 fo… [See Man Page]'

