# klist
# Autogenerated from man page /usr/share/man/man1/klist.1
# using Darwin man parser
complete -c klist -s T --description 'display AFS tokens.'
complete -c klist -s 5 --description 'display v5 cred cache (this is the default).'
complete -c klist -s v --description 'Verbose output.'

