# mtoc
# Autogenerated from man page /opt/local/share/man/man1/mtoc.1.gz
# using Deroffing man parser
complete -c mtoc -o subsystem --description 'specifies the EFI subsystem  type which can be … [See Man Page]'
complete -c mtoc -o section_alignment --description 'Specifies the PECOFF section alignment.'
complete -c mtoc -o align --description 'Specifies the PECOFF file and section alignment.'
complete -c mtoc -o segalign --description 'when linking the Mach-O file.'
complete -c mtoc -s d --description 'Specifies the filename to be used to create a d… [See Man Page]'

