# notmuch-tag
# Autogenerated from man page /opt/local/share/man/man1/notmuch-tag.1.gz
# using Deroffing man parser
complete -c notmuch-tag -l remove-all --description '.'
complete -c notmuch-tag -l batch --description '.'
complete -c notmuch-tag -l input --description '.'

