# notmuch-reply
# Autogenerated from man page /opt/local/share/man/man1/notmuch-reply.1.gz
# using Deroffing man parser
complete -c notmuch-reply -l reply-to --description 'is specified, values from the To: and Cc: heade… [See Man Page]'
complete -c notmuch-reply -l format --description 'default Includes subject and quoted message body.'
complete -c notmuch-reply -l format-version --description '.'
complete -c notmuch-reply -l decrypt --description '.'

