# pandoc-citeproc
# Autogenerated from man page /usr/local/share/man/man1/pandoc-citeproc.1
# using Deroffing man parser
complete -c pandoc-citeproc -l 'help\\f[]' --description 'Print usage information. RS . RE.'
complete -c pandoc-citeproc -l ---------- -l ------------ --description 'MODS              . mods BibLaTeX          .'
complete -c pandoc-citeproc -s h -l help --description 'Print usage information.'
complete -c pandoc-citeproc -s V -l version --description 'Print version.  AUTHORS.'

