# quest
# Autogenerated from man page /opt/local/share/man/man1/quest.1.gz
# using Deroffing man parser
complete -c quest -s d -l db --description 'database to search (multiple databases may be specified).'
complete -c quest -s m -l msize --description 'maximum number of matches to return.'
complete -c quest -s s -l stemmer --description 'set the stemming language, the default is \'engl… [See Man Page]'
complete -c quest -s p -l prefix --description 'Add a prefix.'
complete -c quest -s b -l boolean-prefix --description 'Add a boolean prefix.'
complete -c quest -s h -l help --description 'display this help and exit.'
complete -c quest -s v -l version --description 'output version information and exit.'

