# seg_addr_table
# Autogenerated from man page /opt/local/share/man/man1/seg_addr_table.1.gz
# using Deroffing man parser
complete -c seg_addr_table -s o --description 'Write the new segment address table to  output_file.'
complete -c seg_addr_table -o relayout --description 'This causes the entire table to be re-laied out… [See Man Page]'
complete -c seg_addr_table -o update --description 'Only entries with zero address values are assigned addresses.'
complete -c seg_addr_table -o update_overlaps --description 'Detects overlaps in the table and reassigns the… [See Man Page]'
complete -c seg_addr_table -o relayout_nonsplit --description 'Similar to relayout except it only causes all t… [See Man Page]'
complete -c seg_addr_table -o checkonly --description 'This option only checks the entries in the table for overlaps.'
complete -c seg_addr_table -o seg_addr_table --description 'This is the input segment address table.'
complete -c seg_addr_table -o release --description 'For each ``flat\'\' entry in the table try findin… [See Man Page]'
complete -c seg_addr_table -o seg1addr --description 'Specifies the starting address to layout ``flat\'\' libraries.'
complete -c seg_addr_table -o allocate_flat --description 'Specifies which  direction to allocate flat addresses into.'
complete -c seg_addr_table -o segs_read_only_addr --description 'Specifies the starting address to layout the re… [See Man Page]'
complete -c seg_addr_table -o segs_read_write_addr --description 'Specifies the starting address to layout the re… [See Man Page]'
complete -c seg_addr_table -o disablewarnings --description 'This option disables a small number of warnings… [See Man Page]'
complete -c seg_addr_table -o 'seg1addr.' --description 'In the second form is used for ``split\'\' librar… [See Man Page]'
complete -c seg_addr_table -o arch --description 'Specifies the architecture, arch_type, in the f… [See Man Page]'

