# sqlite3
# Autogenerated from man page /usr/share/man/man1/sqlite3.1
# using Deroffing man parser
complete -c sqlite3 -o initfile --description 'Read and execute commands from  file , which ca… [See Man Page]'

